import { toSafeNumber } from './toSafeNumber';

/**
 * Formats a value with fixed-point precision and removes insignificant
 * trailing zeroes.
 *
 * @remarks
 * The value is first normalized with {@link toSafeNumber}. The formatted
 * result is converted through `Number()`, so trailing zeroes generated by
 * `Number.prototype.toFixed()` are removed.
 *
 * @param num - Number to format.
 * @param fractionDigits - Number of digits to keep after the decimal point.
 * @returns Fixed-point string normalized through `Number()`.
 *
 * @example
 * ```ts
 * toFixed(0.101, 2);
 * // => '0.1'
 * ```
 *
 * @example Formatting a whole number
 * ```ts
 * toFixed(12, 2);
 * // => '12'
 * ```
 *
 * @example Normalizing an invalid number
 * ```ts
 * toFixed(Number.NaN, 2);
 * // => '0'
 * ```
 */
export function toFixed(num: number, fractionDigits?: number): string {
  return Number(toSafeNumber(num).toFixed(fractionDigits)) + '';
}
